[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  SECRETS_SCAN_OMIT_PATHS = ".netlify/**,.wrangler/**,node_modules/**,*.log"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'self' https://admin.charlotteudo.org https://app.netlify.com;"
    X-Frame-Options = "ALLOW-FROM https://admin.charlotteudo.org"
